version: '3.4'

services:
  big-api:
    image: abu116/big-api:v0.0.3-amd64
    platform: linux/amd64  # 指定平台为 amd64
    # build: .
    container_name: big-api
    restart: always
    # command: --log-dir /app/logs  # 移除错误的命令行参数
    ports:
      - "3000:3000"  # 修改端口映射
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - GIN_MODE=release
      # - SQL_DSN=用户名:密码@tcp(ip)/数据库名  # 注释掉此行以使用 SQLite 作为数据库
      - REDIS_CONN_STRING=redis://redis:6379/0
      - SESSION_SECRET=msdsfd61s6f5sdf
      - CRYPTO_SECRET=API_POIUYTREWQ           # 修改为随机字符串
      - TZ=Asia/Shanghai
      - REDIS_POOL_SIZE=10
      - SYNC_FREQUENCY=60
      - SQL_MAX_IDLE_CONNS=10
      - SQL_MAX_OPEN_CONNS=100
      - SQL_MAX_LIFETIME=60
      - LOG_DIR=/app/logs  # 将命令行参数改为环境变量
      - CONFIG_FILE_PATH=/app/config/oauth.json
#      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
#      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
#      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
    depends_on:
      - redis
    networks:
      - bigapi-network

  redis:
    image: redis:alpine
    container_name: veloera-redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
    networks:
      - bigapi-network

networks:
  bigapi-network:
    driver: bridge

